DELIMITER //

DROP PROCEDURE IF EXISTS GETFILES;

CREATE PROCEDURE GETFILES()
BEGIN
    SELECT 
        FILE_ID,
        FILE_NAME, 
        TABLESPACE_NAME,
        STATUS,
        INITIAL_SIZE,
        MAXIMUM_SIZE,
        AUTOEXTEND_SIZE,
        EXTENT_SIZE,
        TOTAL_EXTENTS,
        FREE_EXTENTS
    FROM INFORMATION_SCHEMA.FILES
    ORDER BY FILE_ID;
END;

//

DELIMITER ;