DELIMITER //

DROP PROCEDURE IF EXISTS GETSCHEMAS;

CREATE PROCEDURE GETSCHEMAS()
BEGIN
    SELECT 
        SCHEMA_NAME, 
        DEFAULT_CHARACTER_SET_NAME, 
        DEFAULT_COLLATION_NAME
    FROM INFORMATION_SCHEMA.SCHEMATA
    ORDER BY SCHEMA_NAME;
END;

//

DELIMITER ;