DELIMITER //

DROP PROCEDURE IF EXISTS GETTABLES;

CREATE PROCEDURE GETTABLES(IN PSCHEMA VARCHAR(128))
BEGIN
    SELECT TABLE_NAME , TABLE_TYPE
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = PSCHEMA;
END;

//

DELIMITER ;